In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 5GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Data preprocessing

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
dataset = pd.read_csv('/content/4458_8204_bundle_archive (2).zip')

In [ ]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1599 entries, 0 to 1598
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   fixed acidity         1599 non-null   float64
 1   volatile acidity      1599 non-null   float64
 2   citric acid           1599 non-null   float64
 3   residual sugar        1599 non-null   float64
 4   chlorides             1599 non-null   float64
 5   free sulfur dioxide   1599 non-null   float64
 6   total sulfur dioxide  1599 non-null   float64
 7   density               1599 non-null   float64
 8   pH                    1599 non-null   float64
 9   sulphates             1599 non-null   float64
 10  alcohol               1599 non-null   float64
 11  quality               1599 non-null   int64  
dtypes: float64(11), int64(1)
memory usage: 150.0 KB


In [ ]:
dataset.describe()

fixed acidity  volatile acidity  ...      alcohol      quality
count    1599.000000       1599.000000  ...  1599.000000  1599.000000
mean        8.319637          0.527821  ...    10.422983     5.636023
std         1.741096          0.179060  ...     1.065668     0.807569
min         4.600000          0.120000  ...     8.400000     3.000000
25%         7.100000          0.390000  ...     9.500000     5.000000
50%         7.900000          0.520000  ...    10.200000     6.000000
75%         9.200000          0.640000  ...    11.100000     6.000000
max        15.900000          1.580000  ...    14.900000     8.000000

[8 rows x 12 columns]

In [ ]:
dataset['quality'].unique()

array([5, 6, 7, 4, 8, 3])

# Separate Features and target

In [ ]:
x = dataset.iloc[: , :-1].values
y = dataset.iloc[: , -1].values

In [ ]:
x

array([[ 7.4  ,  0.7  ,  0.   , ...,  3.51 ,  0.56 ,  9.4  ],
       [ 7.8  ,  0.88 ,  0.   , ...,  3.2  ,  0.68 ,  9.8  ],
       [ 7.8  ,  0.76 ,  0.04 , ...,  3.26 ,  0.65 ,  9.8  ],
       ...,
       [ 6.3  ,  0.51 ,  0.13 , ...,  3.42 ,  0.75 , 11.   ],
       [ 5.9  ,  0.645,  0.12 , ...,  3.57 ,  0.71 , 10.2  ],
       [ 6.   ,  0.31 ,  0.47 , ...,  3.39 ,  0.66 , 11.   ]])

In [ ]:
y

array([5, 5, 5, ..., 6, 5, 6])

# Splitting the data into train and test sets

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.20)

# Standardization

In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
sc = StandardScaler()

In [ ]:
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

# Train on different algorithms

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC

In [ ]:
l_cla = LogisticRegression()
d_cla = DecisionTreeClassifier()
r_cla = RandomForestClassifier()
k_cla = KNeighborsClassifier()
s_cla = SVC(kernel='linear')
ks_cla = SVC(kernel='rbf')

In [ ]:
l_cla.fit(x_train, y_train)
k_cla.fit(x_train, y_train)
d_cla.fit(x_train, y_train)
r_cla.fit(x_train, y_train)
s_cla.fit(x_train, y_train)
ks_cla.fit(x_train, y_train)

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [ ]:
l_pred = l_cla.predict(x_test)
k_pred = k_cla.predict(x_test)
d_pred = d_cla.predict(x_test)
r_pred = r_cla.predict(x_test)
s_pred = s_cla.predict(x_test)
ks_pred = ks_cla.predict(x_test)

In [ ]:
from sklearn.metrics import confusion_matrix

In [ ]:
l_c = confusion_matrix(y_test, l_pred)
k_c = confusion_matrix(y_test, k_pred)
d_c = confusion_matrix(y_test, d_pred)
r_c = confusion_matrix(y_test, r_pred)
s_c = confusion_matrix(y_test, s_pred)
ks_c = confusion_matrix(y_test, ks_pred)

In [ ]:
l_c

array([[ 0,  0,  2,  0,  0,  0],
       [ 0,  1,  7,  1,  0,  0],
       [ 0,  0, 92, 32,  1,  0],
       [ 0,  0, 52, 80,  9,  0],
       [ 0,  0,  2, 26, 11,  0],
       [ 0,  0,  0,  3,  1,  0]])

In [ ]:
k_c

array([[ 0,  0,  1,  1,  0,  0],
       [ 0,  1,  6,  2,  0,  0],
       [ 0,  1, 91, 28,  5,  0],
       [ 0,  1, 47, 77, 16,  0],
       [ 0,  0,  4, 12, 23,  0],
       [ 0,  0,  0,  3,  1,  0]])

In [ ]:
d_c

array([[ 0,  0,  0,  2,  0,  0],
       [ 0,  2,  4,  3,  0,  0],
       [ 0,  3, 79, 32,  6,  5],
       [ 0,  1, 29, 88, 22,  1],
       [ 0,  0,  3, 17, 17,  2],
       [ 0,  0,  0,  2,  2,  0]])

In [ ]:
r_c

array([[  0,   0,   1,   1,   0,   0],
       [  0,   0,   7,   2,   0,   0],
       [  0,   1,  94,  29,   1,   0],
       [  0,   0,  28, 103,  10,   0],
       [  0,   0,   2,  19,  18,   0],
       [  0,   0,   0,   3,   1,   0]])

In [ ]:
s_c

array([[ 0,  0,  2,  0,  0,  0],
       [ 0,  0,  8,  1,  0,  0],
       [ 0,  0, 96, 29,  0,  0],
       [ 0,  0, 58, 83,  0,  0],
       [ 0,  0,  2, 37,  0,  0],
       [ 0,  0,  0,  4,  0,  0]])

In [ ]:
ks_c

array([[ 0,  0,  2,  0,  0,  0],
       [ 0,  0,  9,  0,  0,  0],
       [ 0,  0, 91, 32,  2,  0],
       [ 0,  0, 53, 81,  7,  0],
       [ 0,  0,  1, 26, 12,  0],
       [ 0,  0,  0,  3,  1,  0]])

# Result

In [ ]:
from sklearn.metrics import accuracy_score

In [ ]:
l_a = accuracy_score(y_test, l_pred)
k_a = accuracy_score(y_test, k_pred)
d_a = accuracy_score(y_test, d_pred)
r_a = accuracy_score(y_test, r_pred)
s_a = accuracy_score(y_test, s_pred)
ks_a = accuracy_score(y_test, ks_pred)

In [ ]:
print('\nLogistic Regression: ' + str(l_a) + '\nKNN: ' + str(k_a) + '\nDecision Tree: ' + str(d_a) + '\nRandom Forest: ' + str(r_a) + '\Linear SVC: ' + str(s_a) + '\nKernel SVC: ' +str(ks_a))


Logistic Regression: 0.575
KNN: 0.6
Decision Tree: 0.58125
Random Forest: 0.671875\Linear SVC: 0.559375
Kernel SVC: 0.575
